name: Opens a new PR if there are model updates
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  open-router:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git user
        run: |
          git config --local user.email "bot@langchain.com"
          git config --local user.name "OpenRouter Bot"
        
      - name: Create branch
        run: |
          git checkout -b bot/update-open-router origin/main
          git rebase main

      - name: Generate code
        run: |
          cd src/Providers/OpenRouter/tools/LangChain.Providers.OpenRouter.CodeGenerator
          dotnet run --output ../../src

      - name: Check for changes
        id: changes
        run: |
          CHANGED=$(git diff --name-only)
          if [ -z "$CHANGED" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add .
          git commit -m "feat: Updated OpenRouter models"
          git push --force-with-lease -u origin bot/update-open-router

      - name: Wait for 15 seconds
        run: sleep 15
      
      - name: Create pull request
        if: steps.changes.outputs.has_changes == 'true'
        run: gh pr create -B bot/update-open-router -H main --title 'feat:Updated OpenRouter models' --body 'Created by Github Actions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
